--- #YAML:1.0
name:                cpan_bot
version:             0.06
abstract:            an IRC CPAN Info bot
license:             ~
author:              
    - Zoffix Znet <zoffix@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    POE:                           0.9999
    POE::Component::IRC:           5.56
    POE::Component::IRC::Plugin::BotAddressed: 0
    POE::Component::IRC::Plugin::Connector: 0
    POE::Component::IRC::Plugin::CPAN::Info: 0.03
    POE::Component::IRC::Plugin::CPAN::LinksToDocs::No404s: 0.001
    POE::Component::IRC::Plugin::NickReclaim: 0
    POE::Component::IRC::Plugin::PAUSE::RecentUploads: 0.04
    Test::More:                    0
    Test::Script:                  1.02
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
